GET  http://localhost:3004/api/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJrZXZpbkBnbWFpbC5jb20iLCJST0xFU18iOiJBRE1JTiIsImlhdCI6MTY2NDg3NTg1MiwiZXhwIjoxNjY0ODkzODUyfQ.wM4khNPcfNiQ2dhnw0VHUEuKkJGore3vwEj44-d95aw
