GET  http://localhost:3004/api/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJrZXZpbkBnbWFpbC5jb20iLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJpYXQiOjE2NjQ5MDcwMDEsImV4cCI6MTY2NDkyNTAwMX0.aVmQy586_qvs-wuwmJ3wFVRjm2I0MousY_pZ-UWtAKE